server:
  port: 8181

# spring cloud required
spring:
  application:
    name: echo

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8383/eureka
#    fetchRegistry: true

#logging config
logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.uec: DEBUG